apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduverse-chat-deployment
  labels:
    name:  chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - image: nahyan007/eduverse-chat:latest
        name: chat-service
        envFrom:
          - configMapRef:
              name: chat-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: eduverse-chat-service
spec:
  selector:
    app: eduverse-chat-service
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001