apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduverse-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduverse-user-service
  template:
    metadata:
      labels:
        app: eduverse-user-service
    spec:
      containers:
      - name: eduverse-user-service
        image: nahyan007/eduverse-user:latest
        envFrom:
        - configMapRef:
            name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: eduverse-user-service
spec:
  selector:
    app: eduverse-user-service
  ports:
  - protocol: TCP
    port: 6001
    targetPort: 6001